# Generated by Django 5.2.3 on 2025-08-26 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_alter_usuario_options_usuario_ativo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompartilhamentoStreaming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_compartilhamento', models.DateTimeField(auto_now_add=True)),
                ('nivel_acesso', models.CharField(choices=[('leitura', 'Apenas Visualização'), ('acesso', 'Acesso Completo'), ('admin', 'Administrador')], default='leitura', max_length=10)),
                ('ativo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Compartilhamento de Streaming',
                'verbose_name_plural': 'Compartilhamentos de Streaming',
            },
        ),
        migrations.CreateModel(
            name='ContaStreaming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da conta', max_length=100)),
                ('plataforma', models.CharField(choices=[('netflix', 'Netflix'), ('disney', 'Disney+'), ('hbo', 'HBO Max'), ('prime', 'Amazon Prime'), ('paramount', 'Paramount+'), ('starz', 'Starz'), ('apple', 'Apple TV+'), ('hulu', 'Hulu'), ('peacock', 'Peacock'), ('crunchyroll', 'Crunchyroll'), ('funimation', 'Funimation'), ('youtube', 'YouTube Premium'), ('spotify', 'Spotify'), ('deezer', 'Deezer'), ('tidal', 'Tidal'), ('outros', 'Outros')], default='netflix', max_length=20)),
                ('email', models.EmailField(help_text='Email da conta', max_length=254)),
                ('usuario', models.CharField(blank=True, help_text='Nome de usuário (se diferente do email)', max_length=100, null=True)),
                ('senha', models.CharField(help_text='Senha da conta (será criptografada)', max_length=255)),
                ('foto', models.ImageField(blank=True, help_text='Foto/logo da plataforma', null=True, upload_to='streaming_fotos/')),
                ('descricao', models.TextField(blank=True, help_text='Descrição adicional da conta', null=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('pendente', 'Pendente'), ('expirado', 'Expirado')], default='ativo', max_length=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_expiracao', models.DateField(blank=True, help_text='Data de expiração da conta', null=True)),
                ('ultimo_acesso', models.DateTimeField(blank=True, help_text='Último acesso à conta', null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('compartilhado_com', models.ManyToManyField(blank=True, help_text='Usuários com quem esta conta é compartilhada', related_name='contas_compartilhadas', through='steam.CompartilhamentoStreaming', to='usuarios.usuario')),
                ('proprietario', models.ForeignKey(help_text='Usuário que criou/possui esta conta', on_delete=django.db.models.deletion.CASCADE, related_name='contas_streaming', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Conta de Streaming',
                'verbose_name_plural': 'Contas de Streaming',
                'ordering': ['-data_criacao'],
                'unique_together': {('email', 'plataforma', 'proprietario')},
            },
        ),
        migrations.AddField(
            model_name='compartilhamentostreaming',
            name='conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steam.contastreaming'),
        ),
        migrations.CreateModel(
            name='HistoricoAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_acesso', models.DateTimeField(auto_now_add=True)),
                ('ip_acesso', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('sucesso', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steam.contastreaming')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Histórico de Acesso',
                'verbose_name_plural': 'Histórico de Acessos',
                'ordering': ['-data_acesso'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='compartilhamentostreaming',
            unique_together={('conta', 'usuario')},
        ),
    ]
